driver: don't call MODULE_SUPPORTED_DEVICE
Problem: compliation fails with linux-5.13

parport_gpio.c:448:25: error: expected declaration specifiers or ‘...’ before string constant
  448 | MODULE_SUPPORTED_DEVICE("Raspberry Pi GPIO Parallel Port HAT");
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Stop using the MODULE_SUPPORTED_DEVICE macro, which was removed by
torvalds/linux@6417f03132a6952cd17ddd8eaddbac92b61b17e0